const data={
    products: [
        {
            name:'iPhone jpro',
            slug:'iphone-jpro',
            category:'Electronics',
            image:'/images/iphone 13 pro.png',
            Price:'10,000',
            countInstock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'latest featured Mobile',
        },
        {
            name:'lenova ipad pro',
            slug:'ipad-pro',
            category:'Electronics',
            image:'/images/ipad.png',
            Price:'40,000',
            countInstock:10,
            brand:'lenova',
            rating:4.0,
            numReviews:10,
            description:'Flexible iPad',
        },
        {
            name:'Zio Air pods 138',
            slug:'Air-pods',
            category:'Electronics',
            image:'/images/airpods.png',
            Price:'3,000',
            countInstock:10,
            brand:'Zio',
            rating:4.7,
            numReviews:10,
            description:'Bluetooth Pods',
        },
        {
            name:'Hp LaptopE41-25',
            slug:'hp-laptop-E41-25',
            category:'Electronics',
            image:'/images/laptop.png',
            Price:'80,000',
            countInstock:10,
            brand:'Hp',
            rating:5,
            numReviews:10,
            description:'latest featured Mobile',
        },
        {
            name:'Itec PC monitor',
            slug:'2inch-hightec-PC-monitor',
            category:'Electronics',
            image:'/images/pcm1.png',
            Price:'35,000',
            countInstock:10,
            brand:'Hightec',
            rating:4.2,
            numReviews:10,
            description:'HD fullscreen Monitor',
        },
        {
            name:'H6 Smart watch',
            slug:'smart-watch',
            category:'Electronics',
            image:'/images/w1.png',
            Price:'15,000',
            countInstock:10,
            brand:'H6',
            rating:5,
            numReviews:10,
            description:'handy calc watch',
        },
        {
            name:'HD Dslr Camera',
            slug:'dslr-cam',
            category:'Electronics',
            image:'/images/dslr camera.png',
            Price:'24,000',
            countInstock:10,
            brand:'Dslr',
            rating:4.5,
            numReviews:10,
            description:'fast Capturing',
        },
        {
            name:'ESS1 Headphones',
            slug:'headpones',
            category:'Electronics',
            image:'/images/h1.png',
            Price:'3,990',
            countInstock:10,
            brand:'ESS1',
            rating:4.5,
            numReviews:10,
            description:'Enjoy in your world ',
        },
    ],
};

export default data;